export const municipalityIdMapping = new Map([
    ["bangued-abra", 1],
    ["boliney-abra", 2],
    ["bucay-abra", 3],
    ["bucloc-abra", 4],
    ["daguioman-abra", 5],
    ["danglas-abra", 6],
    ["dolores-abra", 7],
    ["la paz-abra", 8],
    ["lacub-abra", 9],
    ["lagangilang-abra", 10],
    ["lagayan-abra", 11],
    ["langiden-abra", 12],
    ["licuan-baay (licuan)-abra", 13],
    ["luba-abra", 14],
    ["malibcong-abra", 15],
    ["manabo-abra", 16],
    ["peñarrubia-abra", 17],
    ["pidigan-abra", 18],
    ["pilar-abra", 19],
    ["sallapadan-abra", 20],
    ["san isidro-abra", 21],
    ["san juan-abra", 22],
    ["san quintin-abra", 23],
    ["tayum-abra", 24],
    ["tineg-abra", 25],
    ["tubo-abra", 26],
    ["villaviciosa-abra", 27],
    ["calanasan-apayao", 28],
    ["conner-apayao", 29],
    ["flora-apayao", 30],
    ["kabugao-apayao", 31],
    ["luna-apayao", 32],
    ["pudtol-apayao", 33],
    ["santa marcela-apayao", 34],
    ["atok-benguet", 35],
    ["baguio-benguet", 36],
    ["bakun-benguet", 37],
    ["bokod-benguet", 38],
    ["buguias-benguet", 39],
    ["itogon-benguet", 40],
    ["kabayan-benguet", 41],
    ["kapangan-benguet", 42],
    ["kibungan-benguet", 43],
    ["la trinidad (capital)-benguet", 44],
    ["mankayan-benguet", 45],
    ["sablan-benguet", 46],
    ["tuba-benguet", 47],
    ["tublay-benguet", 48],
    ["banaue-ifugao", 49],
    ["hungduan-ifugao", 50],
    ["kiangan-ifugao", 51],
    ["lagawe (capital)-ifugao", 52],
    ["lamut-ifugao", 53],
    ["mayoyao-ifugao", 54],
    ["alfonso lista (potia)-ifugao", 55],
    ["aguinaldo-ifugao", 56],
    ["hingyon-ifugao", 57],
    ["tinoc-ifugao", 58],
    ["asipulo-ifugao", 59],
    ["balbalan-kalinga", 60],
    ["lubuagan-kalinga", 61],
    ["pasil-kalinga", 62],
    ["pinukpuk-kalinga", 63],
    ["rizal (liwan)-kalinga", 64],
    ["city of tabuk (capital)-kalinga", 65],
    ["tanudan-kalinga", 66],
    ["tinglayan-kalinga", 67],
    ["barlig-mountain province", 68],
    ["bauko-mountain province", 69],
    ["besao-mountain province", 70],
    ["bontoc (capital)-mountain province", 71],
    ["natonin-mountain province", 72],
    ["paracelis-mountain province", 73],
    ["sabangan-mountain province", 74],
    ["sadanga-mountain province", 75],
    ["sagada-mountain province", 76],
    ["tadian-mountain province", 77],
]);

export function getIdByMunicipalityName(chosenMunicipality){
    return municipalityIdMapping.get(chosenMunicipality);
}